services:
  recipeapp_app: 
    build: .
    container_name: recipe_app
    depends_on: 
      recipeapp_db:
        condition: service_healthy
    ports: 
      - '8000:8000'
    volumes:
      - .:/django
  recipeapp_db:
    container_name: recipe_db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data