services:
  recipeapp_app: 
    build: .
    ports: 
      - '8000:8000'
    volumes:
      - .:/django
  recipeapp_db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/posgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: